In [4]:
import pandas as pd
import numpy as np

In [5]:
import gdown  ##코드랩에서는 구글을 기본으로 쓰다보니까 자동으로 gdown이 깔려있지만, 아나콘다에서는 아니므로 cmd에서 gdown을 깔아줘야함.



ModuleNotFoundError: No module named 'gdown'

In [6]:
import gdown

In [64]:
gdown.download('https://bit.ly/3RhoNho', 'ns_202104.csv',quiet=False) ##그런데 경로와 파일명을 알고 있기 때문에 굳이 gdown.download()을 쓰지 않고 아래의 판다스의 

Downloading...
From: https://bit.ly/3RhoNho
To: c:\work\ns_202104.csv
100%|█████████████████████████████████████████████████████████████████████████████| 57.6M/57.6M [00:06<00:00, 8.68MB/s]


'ns_202104.csv'

In [114]:
df = pd.read_csv('https://bit.ly/3RhoNho')

C:\Users\user\AppData\Local\Temp\ipykernel_29736\369920610.py:1: DtypeWarning: Columns (5,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('https://bit.ly/3RhoNho')


In [116]:
df.head()

번호                    도서명                저자    출판사  발행년도           ISBN  \
0   1                인공지능과 흙            김동훈 지음    민음사  2021  9788937444319   
1   2           가짜 행복 권하는 사회            김태형 지음   갈매나무  2021  9791190123969   
2   3  나도 한 문장 잘 쓰면 바랄 게 없겠네            김선영 지음   블랙피쉬  2021  9788968332982   
3   4                예루살렘 해변  이도 게펜 지음, 임재희 옮김  문학세계사  2021  9788970759906   
4   5  김성곤의 중국한시기행 : 장강·황하 편            김성곤 지음    김영사  2021  9788934990833   

  세트 ISBN 부가기호    권 주제분류번호  도서권수  대출건수        등록일자  Unnamed: 13  
0     NaN  NaN  NaN    NaN     1     0  2021-03-19          NaN  
1     NaN  NaN  NaN    NaN     1     0  2021-03-19          NaN  
2     NaN  NaN  NaN    NaN     1     0  2021-03-19          NaN  
3     NaN  NaN  NaN    NaN     1     0  2021-03-19          NaN  
4     NaN  NaN  NaN    NaN     1     0  2021-03-19          NaN

In [68]:
df.shape

(401682, 14)

In [79]:
df.columns  #열의 index를 리스트형으로 불러옴.

Index(['번호', '도서명', '저자', '출판사', '발행년도', 'ISBN', '세트 ISBN', '부가기호', '권',
       '주제분류번호', '도서권수', '대출건수', '등록일자', 'Unnamed: 13'],
      dtype='object')

In [93]:
df.columns[-1]  #df.columns리스트에서 -1자리의 값을 불러옴.

'Unnamed: 13'

In [71]:
df.columns
len(df.columns)
df.shape[1]
df.columns.size

14

In [91]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [92]:
np.arange(13) == 1

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False])

In [96]:
df.columns == df.columns[-1]

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True])

In [97]:
~(df.columns == df.columns[-1])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False])

In [85]:
[True]*13+[False]

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False]

In [90]:
# iloc은 index를 기준으로 범위를 잡는다.
# df.iloc[:,:-1] 은 [행 전체, 열은 0부터 -1번까지]로 범위를 잡는다는 뜻이다.

df.iloc[:,:-1].head()
df.iloc[:,:df.columns.size-1].head()
df.iloc[:,np.arange(13)].head()

번호                    도서명                저자    출판사  발행년도           ISBN  \
0   1                인공지능과 흙            김동훈 지음    민음사  2021  9788937444319   
1   2           가짜 행복 권하는 사회            김태형 지음   갈매나무  2021  9791190123969   
2   3  나도 한 문장 잘 쓰면 바랄 게 없겠네            김선영 지음   블랙피쉬  2021  9788968332982   
3   4                예루살렘 해변  이도 게펜 지음, 임재희 옮김  문학세계사  2021  9788970759906   
4   5  김성곤의 중국한시기행 : 장강·황하 편            김성곤 지음    김영사  2021  9788934990833   

  세트 ISBN 부가기호    권 주제분류번호  도서권수  대출건수        등록일자  
0     NaN  NaN  NaN    NaN     1     0  2021-03-19  
1     NaN  NaN  NaN    NaN     1     0  2021-03-19  
2     NaN  NaN  NaN    NaN     1     0  2021-03-19  
3     NaN  NaN  NaN    NaN     1     0  2021-03-19  
4     NaN  NaN  NaN    NaN     1     0  2021-03-19

In [102]:
# loc은 column명 index을 기준으로 범위를 잡아 보여준다.
# df.loc[:,'번호':'등록일자'] 은 [행 전체, 열은 번호부터 등록일자까지]로 범위를 잡는다는 뜻이다.
# loc은 column이 True인 경우에 출력함.

df.loc[:,'번호':'등록일자'].head()
df.loc[:,:'등록일자'].head()
df.loc[:,df.columns[:-1]].head()
df.loc[:,[True]*13+[False]].head()
df.loc[:,~(df.columns == df.columns[-1])].head()
df.loc[:,df.columns != df.columns[-1]].head()

번호                    도서명                저자    출판사  발행년도           ISBN  \
0   1                인공지능과 흙            김동훈 지음    민음사  2021  9788937444319   
1   2           가짜 행복 권하는 사회            김태형 지음   갈매나무  2021  9791190123969   
2   3  나도 한 문장 잘 쓰면 바랄 게 없겠네            김선영 지음   블랙피쉬  2021  9788968332982   
3   4                예루살렘 해변  이도 게펜 지음, 임재희 옮김  문학세계사  2021  9788970759906   
4   5  김성곤의 중국한시기행 : 장강·황하 편            김성곤 지음    김영사  2021  9788934990833   

  세트 ISBN 부가기호    권 주제분류번호  도서권수  대출건수        등록일자  
0     NaN  NaN  NaN    NaN     1     0  2021-03-19  
1     NaN  NaN  NaN    NaN     1     0  2021-03-19  
2     NaN  NaN  NaN    NaN     1     0  2021-03-19  
3     NaN  NaN  NaN    NaN     1     0  2021-03-19  
4     NaN  NaN  NaN    NaN     1     0  2021-03-19

In [117]:
# drop은 빼고 싶은 것을 적어준다.

df.drop(columns=['Unnamed: 13']).head()
df.drop(columns=df.columns[-1]).head()
df.drop(['Unnamed: 13'], axis=1).head()

번호                    도서명                저자    출판사  발행년도           ISBN  \
0   1                인공지능과 흙            김동훈 지음    민음사  2021  9788937444319   
1   2           가짜 행복 권하는 사회            김태형 지음   갈매나무  2021  9791190123969   
2   3  나도 한 문장 잘 쓰면 바랄 게 없겠네            김선영 지음   블랙피쉬  2021  9788968332982   
3   4                예루살렘 해변  이도 게펜 지음, 임재희 옮김  문학세계사  2021  9788970759906   
4   5  김성곤의 중국한시기행 : 장강·황하 편            김성곤 지음    김영사  2021  9788934990833   

  세트 ISBN 부가기호    권 주제분류번호  도서권수  대출건수        등록일자  
0     NaN  NaN  NaN    NaN     1     0  2021-03-19  
1     NaN  NaN  NaN    NaN     1     0  2021-03-19  
2     NaN  NaN  NaN    NaN     1     0  2021-03-19  
3     NaN  NaN  NaN    NaN     1     0  2021-03-19  
4     NaN  NaN  NaN    NaN     1     0  2021-03-19

In [ ]:
df.iloc[:,'번호':'등록일자'].head  ##불가

In [ ]:
df.iloc[:,:].head()

In [16]:
df.isna().sum()

번호                  0
도서명               403
저자                201
출판사              4795
발행년도               17
ISBN                0
세트 ISBN        339811
부가기호            76648
권              333415
주제분류번호          20322
도서권수                0
대출건수                0
등록일자                0
Unnamed: 13    401682
dtype: int64

In [17]:
df.isna().sum()/df.shape[0] > 0.7

번호             False
도서명            False
저자             False
출판사            False
발행년도           False
ISBN           False
세트 ISBN         True
부가기호           False
권               True
주제분류번호         False
도서권수           False
대출건수           False
등록일자           False
Unnamed: 13     True
dtype: bool

In [18]:
df.columns[df.isna().sum()/df.shape[0] > 0.7]

Index(['세트 ISBN', '권', 'Unnamed: 13'], dtype='object')

In [24]:
df.drop(columns = df.columns[df.isna().sum()/df.shape[0] > 0.7])

번호                    도서명                저자    출판사  발행년도  \
0            1                인공지능과 흙            김동훈 지음    민음사  2021   
1            2           가짜 행복 권하는 사회            김태형 지음   갈매나무  2021   
2            3  나도 한 문장 잘 쓰면 바랄 게 없겠네            김선영 지음   블랙피쉬  2021   
3            4                예루살렘 해변  이도 게펜 지음, 임재희 옮김  문학세계사  2021   
4            5  김성곤의 중국한시기행 : 장강·황하 편            김성곤 지음    김영사  2021   
...        ...                    ...               ...    ...   ...   
401677  401678                韓國現代詩大系            채만묵 編著  한국문화사  1996   
401678  401679                  뉴 웨이브        제임스 모나코 지음    한나래  1996   
401679  401680           (최인훈 장편소설)화두            최인훈 지음    민음사  1994   
401680  401681           독일 문학과 세계 문학            吳漢鎭 編著     벽호  1995   
401681  401682             참으로 소중한 생각            김일상 지음    동문사  1995   

                 ISBN 부가기호   주제분류번호  도서권수  대출건수        등록일자  
0       9788937444319  NaN      NaN     1     0  2021-03-19  
1       9791190123969  NaN      NaN     1     0  2021-03-19  
2       9788968332982  NaN      NaN     1     0  2021-03-19  
3       9788970759906  NaN      NaN     1     0  2021-03-19  
4       9788934990833  NaN      NaN     1     0  2021-03-19  
...               ...  ...      ...   ...   ...         ...  
401677  9788977352971  NaN  811.608     1     0  1970-01-01  
401678  9788985367448  NaN   688.04     1     0  1970-01-01  
401679  9788937401596  NaN    813.6     1     0  1970-01-01  
401680  9788947700368  NaN   809.05     2     0  1970-01-01  
401681  9788970610092    0    814.6     0     0  1970-01-01  

[401682 rows x 11 columns]

In [25]:
new_df = df.drop(columns = df.columns[df.isna().sum()/df.shape[0] > 0.7])

In [26]:
new_df.isna().sum(1)

0         2
1         2
2         2
3         2
4         2
         ..
401677    1
401678    1
401679    1
401680    1
401681    0
Length: 401682, dtype: int64

In [27]:
new_df.isna().sum(1)/df.shape[1] > 0.2

0         False
1         False
2         False
3         False
4         False
          ...  
401677    False
401678    False
401679    False
401680    False
401681    False
Length: 401682, dtype: bool

In [28]:
new_df.loc[new_df.isna().sum(1)/df.shape[1] > 0.2]

번호                       도서명               저자  출판사  발행년도  \
277        278               골목의 시간을 그리다       정명섭.김효찬 지음  NaN  2021   
366        367                    한국인의 맛           정명섭 지음  NaN  2021   
551        552              한성부, 달 밝은 밤에           김이삭 지음  NaN  2021   
619        620  100일 완성 마그마 러시아어 중고급 단어장  러포자 구제 연구소 외 지음  NaN  2021   
658        659        수채 과슈로 그리는 나의 반려식물           송현미 지음  NaN  2021   
...        ...                       ...              ...  ...   ...   
400367  400368           아무도 모를거야 내가 누군지   김향금 글 ; 이혜리 그림  NaN  1999   
400374  400375                     바람과 물              임억규  NaN  2011   
400375  400376                      자기분석         L. 론 허버드  NaN  2009   
400395  400396                  인천문화예술연감           인천문화재단  NaN  2010   
400408  400409                 걸어오길 잘했어요              전세중  NaN  2010   

                 ISBN 부가기호 주제분류번호  도서권수  대출건수        등록일자  
277     9791191266054  NaN    NaN     1     0  2021-03-12  
366     9791155401804  NaN    NaN     1     0  2021-03-12  
551     9791163161479  NaN    NaN     1     0  2021-03-12  
619     9788974829193  NaN    NaN     1     0  2021-03-12  
658     9791187616986  NaN    NaN     1     0  2021-03-12  
...               ...  ...    ...   ...   ...         ...  
400367  9788943303483  NaN    NaN     1     0  1970-01-01  
400374  9788989358855  NaN    NaN     1     0  1970-01-01  
400375  9781403172662  NaN    NaN     2     0  1970-01-01  
400395  9788992678278  NaN    NaN     1     0  1970-01-01  
400408  3000000000182  NaN    NaN     1     0  1970-01-01  

[607 rows x 11 columns]

In [ ]:
#########################

In [29]:
df.isna().sum()/df.shape[0]

번호             0.000000
도서명            0.001003
저자             0.000500
출판사            0.011937
발행년도           0.000042
ISBN           0.000000
세트 ISBN        0.845970
부가기호           0.190818
권              0.830047
주제분류번호         0.050592
도서권수           0.000000
대출건수           0.000000
등록일자           0.000000
Unnamed: 13    1.000000
dtype: float64

In [30]:
remove_cols = df.columns[df.isna().sum()/df.shape[0]>0.7]

In [32]:
df.drop(columns = remove_cols, inplace = True)

In [33]:
remove_row = ((df.isna().sum(axis = 1)/df.shape[1]) > 0.2)

In [ ]:
df = df.loc[remove_raw, :]

In [34]:
test= pd.read_csv('test.csv')  #데이터프레임 형태로 가져온다.

In [118]:
#눈으로 데이터값 확인
test.head()

이름  나이  방문횟수  방문횟수비율  성별
0  김담향  33     5    0.15  여자
1  이재빈  25    10    0.40  남자
2  김나영  26     4    0.15  여자

In [119]:
#dataframe의 정체를 확인
test.shape

(3, 5)

In [ ]:
#data구성
test.dtypes

#변수 구성
test.columns

#변수 가져오기
test.나이
type(test.나이)

#연평균방문횟수
test.방문횟수 / test.나이

#딕셔너리(dic) {key : value}
#dic[key] -> value
#dic[value] = key -> 딕에 추가

test['방문횟수비율'] = test.방문횟수 / test.나이

#소수점자릿수 지정하기 
#round(10.333 , 2)  -> 10.33

round(test.방문횟수비율,2) # ->가능
test

test['방문횟수비율'] = round(test.방문횟수비율,2) 

#성별 추가하기 #열 추가(column을 추가시킴.) 인덱스를 기준으로 매칭시킨다.
test['성별'] = '여자'

test

In [48]:

test.iloc[1,4]

'여자'

In [49]:
#고치기
test.iloc[1,4] = '남성'
test

이름  나이  방문횟수  방문횟수비율  성별
0  김담향  33     5    0.15  여자
1  이재빈  25    10    0.40  남성
2  김나영  26     4    0.15  여자

In [50]:
#고치기
test.loc[[False, True, False], :]

이름  나이  방문횟수  방문횟수비율  성별
1  이재빈  25    10     0.4  남성

In [51]:
test.loc[[False, True, False], '성별']

1    남성
Name: 성별, dtype: object

In [55]:
print(test)
test.loc[test.이름 =='이재빈', '성별'] 

    이름  나이  방문횟수  방문횟수비율  성별
0  김담향  33     5    0.15  여자
1  이재빈  25    10    0.40  남성
2  김나영  26     4    0.15  여자


1    남성
Name: 성별, dtype: object

In [120]:
test.loc[test.이름 =='이재빈', '성별'] = '남자'
print(test)

    이름  나이  방문횟수  방문횟수비율  성별
0  김담향  33     5    0.15  여자
1  이재빈  25    10    0.40  남자
2  김나영  26     4    0.15  여자


In [122]:
#행추가 컬럼명을 기준으로 매칭시킨다.
new_dic = {'이름':['김건우'], 
'나이':[28],
'방문횟수': [10],
'방문횟수비율' : [10/28],
'성별':['남자']}

new_member = pd.DataFrame(new_dic)

In [ ]:
test['성별']  # 시리즈 데이터
test['성별'].shape
test[['성별']]#데이터 프레임 
test[['성별']].shape

In [123]:
test1 =pd.DataFrame(
                    {
                        '이름':['명하영', '강다솜', '조가영'], 
                        '나이':[27,28,27],
                        '방문횟수':[8,9,np.nan]
                    }
                    )
test1

이름  나이  방문횟수
0  명하영  27   8.0
1  강다솜  28   9.0
2  조가영  27   NaN

In [ ]:
##90이상은 'A'
